# Generated by Django 2.0.2 on 2018-02-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Confectionery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField()),
                ('created', models.DateField(auto_now_add=True)),
                ('first_image', models.ImageField(blank=True, upload_to='product/')),
                ('second_image', models.ImageField(blank=True, upload_to='product/')),
                ('third_image', models.ImageField(blank=True, upload_to='product/')),
                ('fourth_image', models.ImageField(blank=True, upload_to='product/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='confectionery',
            name='ingredients',
            field=models.ManyToManyField(to='shop.Ingredient'),
        ),
    ]
